using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace SdlToolchain;

internal sealed partial class BindingPipeline(
    ToolchainManifest manifest,
    SourceCheckout sources,
    CliInvocation invocation,
    CancellationToken cancellationToken)
{
    private const string SimultaneousGpuTextureFlag =
        "SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE";

    public async Task GenerateAsync()
    {
        var c2ffi = await ResolveC2FfiAsync();
        var sdlRoot = await sources.GetSdlAsync();
        var generatorSourceRoot = await sources.GetBindingGeneratorAsync();
        var generatorRoot = CreateGeneratorWorkingCopy(generatorSourceRoot);

        try
        {
            await GenerateFromWorkingCopyAsync(sdlRoot, generatorRoot, c2ffi);
        }
        finally
        {
            TryDeleteGeneratorWorkingCopy(generatorRoot);
        }
    }

    private async Task GenerateFromWorkingCopyAsync(string sdlRoot, string generatorRoot, string c2ffi)
    {
        PrepareGenerator(generatorRoot, sdlRoot);

        var bindingWorkRoot = Path.Combine(manifest.ArtifactsRoot, "work", "bindings", manifest.Sdl.Version);
        Directory.CreateDirectory(bindingWorkRoot);
        var inputFile = Path.Combine(bindingWorkRoot, "sdl-bindings-input.c");
        var ffiJson = Path.Combine(generatorRoot, "GenerateBindings", "assets", "ffi.json");

        var input = new StringBuilder();
        input.AppendLine("// Generated by Tools/SdlToolchain. Do not edit.");
        foreach (var header in manifest.Bindings.Headers)
        {
            input.Append("#include <").Append(header).AppendLine(">");
        }

        File.WriteAllText(inputFile, input.ToString());
        Directory.CreateDirectory(Path.GetDirectoryName(ffiJson)!);

        await ProcessRunner.RunAsync(
            c2ffi,
            ["--fail-on-error", "-I", Path.Combine(sdlRoot, "include"), inputFile, "-o", ffiJson],
            bindingWorkRoot,
            cancellationToken);

        var dotnet = ProcessRunner.FindExecutable("dotnet")
            ?? throw new ToolchainException("dotnet PATH üzerinde bulunamadı.");
        var generatorProject = Path.Combine(generatorRoot, "GenerateBindings", "GenerateBindings.csproj");
        await ProcessRunner.RunAsync(
            dotnet,
            ["run", "--project", generatorProject, "--configuration", "Release", "--", sdlRoot, "--core"],
            generatorRoot,
            cancellationToken);

        var upstreamOutput = Path.Combine(generatorRoot, "SDL3", "SDL3.Core.cs");
        if (!File.Exists(upstreamOutput))
        {
            throw new ToolchainException($"Binding üreticisi beklenen dosyayı oluşturmadı: {upstreamOutput}");
        }

        var transformed = TransformGeneratedBinding(File.ReadAllText(upstreamOutput));
        var warnings = CountWarnings(transformed);

        var stagedOutput = Path.Combine(manifest.ArtifactsRoot, "generated", "bindings", "SDL3.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(stagedOutput)!);
        File.WriteAllText(stagedOutput, transformed);
        ValidateWarnings(warnings);

        var projectOutput = manifest.ResolvePath(manifest.Bindings.Output);
        Directory.CreateDirectory(Path.GetDirectoryName(projectOutput)!);
        var temporaryOutput = $"{projectOutput}.tmp-{Guid.NewGuid():N}";
        try
        {
            File.Copy(stagedOutput, temporaryOutput, overwrite: false);
            File.Move(temporaryOutput, projectOutput, overwrite: true);
        }
        finally
        {
            if (File.Exists(temporaryOutput))
            {
                File.Delete(temporaryOutput);
            }
        }

        await WriteProvenanceAsync(sdlRoot, c2ffi, warnings, transformed);
        ReportGpuHelperStatus(transformed);
        Console.WriteLine($"Binding güncellendi: {projectOutput}");
    }

    private string CreateGeneratorWorkingCopy(string sourceRoot)
    {
        var parent = Path.Combine(manifest.ArtifactsRoot, "work", "generator");
        var destination = Path.Combine(parent, $"{manifest.Bindings.GeneratorCommit[..12]}-{Guid.NewGuid():N}");
        Directory.CreateDirectory(destination);

        try
        {
            CopyDirectory(sourceRoot, destination);
            return destination;
        }
        catch
        {
            Directory.Delete(destination, recursive: true);
            throw;
        }
    }

    private static void CopyDirectory(string source, string destination)
    {
        foreach (var directory in Directory.EnumerateDirectories(source, "*", SearchOption.AllDirectories))
        {
            var relative = Path.GetRelativePath(source, directory);
            if (ShouldSkipGeneratorPath(relative))
            {
                continue;
            }

            Directory.CreateDirectory(Path.Combine(destination, relative));
        }

        foreach (var file in Directory.EnumerateFiles(source, "*", SearchOption.AllDirectories))
        {
            var relative = Path.GetRelativePath(source, file);
            if (ShouldSkipGeneratorPath(relative))
            {
                continue;
            }

            var target = Path.Combine(destination, relative);
            Directory.CreateDirectory(Path.GetDirectoryName(target)!);
            File.Copy(file, target, overwrite: false);
        }
    }

    private static bool ShouldSkipGeneratorPath(string relativePath)
    {
        return relativePath
            .Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
            .Any(segment => segment is ".git" or "bin" or "obj");
    }

    private static void TryDeleteGeneratorWorkingCopy(string path)
    {
        try
        {
            if (Directory.Exists(path))
            {
                Directory.Delete(path, recursive: true);
            }
        }
        catch (IOException exception)
        {
            Console.WriteLine($"UYARI: Geçici generator çalışma kopyası temizlenemedi: {path} ({exception.Message})");
        }
        catch (UnauthorizedAccessException exception)
        {
            Console.WriteLine($"UYARI: Geçici generator çalışma kopyası temizlenemedi: {path} ({exception.Message})");
        }
    }

    public async Task<string> BootstrapC2FfiAsync()
    {
        var cmake = ProcessRunner.FindExecutable("cmake")
            ?? throw new ToolchainException(
                $"c2ffi derlemek için cmake bulunamadı. LLVM/Clang {manifest.Bindings.C2FfiLlvmVersion} geliştirme paketleri de gerekli.");
        var sourceRoot = await sources.GetC2FfiAsync();
        var buildRoot = Path.Combine(manifest.ArtifactsRoot, "build", "c2ffi", manifest.Bindings.C2FfiCommit[..12]);
        Directory.CreateDirectory(buildRoot);

        var configureArguments = new List<string>
        {
            "-S", sourceRoot,
            "-B", buildRoot,
            "-DCMAKE_BUILD_TYPE=Release"
        };
        var explicitCmakeArguments = invocation.Values("--c2ffi-cmake-arg");
        await AddDetectedLlvmArgumentsAsync(configureArguments, explicitCmakeArguments);
        configureArguments.AddRange(explicitCmakeArguments);

        await ProcessRunner.RunAsync(cmake, configureArguments, manifest.RepositoryRoot, cancellationToken);
        await ProcessRunner.RunAsync(
            cmake,
            ["--build", buildRoot, "--config", "Release"],
            manifest.RepositoryRoot,
            cancellationToken);

        return FindBuiltC2Ffi(buildRoot)
            ?? throw new ToolchainException($"c2ffi derlendi ancak çalıştırılabilir dosya bulunamadı: {buildRoot}");
    }

    private async Task AddDetectedLlvmArgumentsAsync(
        List<string> configureArguments,
        IReadOnlyList<string> explicitArguments)
    {
        var installation = await LlvmDiscovery.FindAsync(
            manifest.Bindings.C2FfiLlvmVersion,
            manifest.RepositoryRoot,
            cancellationToken);
        if (installation is null)
        {
            return;
        }

        AddDefinitionIfMissing(
            configureArguments,
            explicitArguments,
            "LLVM_DIR",
            installation.LlvmCmakeDirectory);
        AddDefinitionIfMissing(
            configureArguments,
            explicitArguments,
            "Clang_DIR",
            installation.ClangCmakeDirectory);
        AddDefinitionIfMissing(
            configureArguments,
            explicitArguments,
            "CLANG_EXECUTABLE",
            installation.ClangExecutable);
        AddDefinitionIfMissing(
            configureArguments,
            explicitArguments,
            "CMAKE_CXX_COMPILER",
            installation.ClangCxxCompiler);

        Console.WriteLine($"LLVM/Clang {installation.Version} otomatik bulundu: {installation.ConfigExecutable}");
    }

    private static void AddDefinitionIfMissing(
        ICollection<string> configureArguments,
        IReadOnlyList<string> explicitArguments,
        string name,
        string? value)
    {
        if (value is null ||
            explicitArguments.Any(argument => argument.StartsWith($"-D{name}=", StringComparison.Ordinal)))
        {
            return;
        }

        configureArguments.Add($"-D{name}={value}");
    }

    private async Task<string> ResolveC2FfiAsync()
    {
        var explicitPath = invocation.Value("--c2ffi");
        if (explicitPath is not null)
        {
            var fullPath = ProcessRunner.FindExecutable(explicitPath)
                ?? Path.GetFullPath(explicitPath, manifest.RepositoryRoot);
            if (!File.Exists(fullPath))
            {
                throw new ToolchainException($"--c2ffi yolu bulunamadı: {fullPath}");
            }

            return fullPath;
        }

        var cachedBuild = Path.Combine(manifest.ArtifactsRoot, "build", "c2ffi", manifest.Bindings.C2FfiCommit[..12]);
        var cached = FindBuiltC2Ffi(cachedBuild);
        if (cached is not null)
        {
            return cached;
        }

        if (invocation.Has("--no-bootstrap"))
        {
            throw new ToolchainException("c2ffi bulunamadı ve --no-bootstrap verildi.");
        }

        Console.WriteLine("c2ffi bulunamadı; manifestte sabitlenen kaynak derlenecek.");
        return await BootstrapC2FfiAsync();
    }

    private static string? FindBuiltC2Ffi(string buildRoot)
    {
        var executableName = OperatingSystem.IsWindows() ? "c2ffi.exe" : "c2ffi";
        var candidates = new[]
        {
            Path.Combine(buildRoot, "bin", executableName),
            Path.Combine(buildRoot, "bin", "Release", executableName),
            Path.Combine(buildRoot, "Release", executableName)
        };
        return candidates.FirstOrDefault(File.Exists);
    }

    private static void PrepareGenerator(string generatorRoot, string sdlRoot)
    {
        PatchTargetFramework(Path.Combine(generatorRoot, "GenerateBindings", "GenerateBindings.csproj"));
        PatchTargetFramework(Path.Combine(generatorRoot, "SDL3", "SDL3.Core.csproj"));

        var gpuHeader = Path.Combine(sdlRoot, "include", "SDL3", "SDL_gpu.h");
        var userProvidedData = Path.Combine(generatorRoot, "GenerateBindings", "UserProvidedData.cs");
        if (!File.ReadAllText(gpuHeader).Contains(SimultaneousGpuTextureFlag, StringComparison.Ordinal))
        {
            return;
        }

        var text = File.ReadAllText(userProvidedData);
        if (text.Contains(SimultaneousGpuTextureFlag, StringComparison.Ordinal))
        {
            return;
        }

        const string anchor = "                \"SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE\",";
        if (!text.Contains(anchor, StringComparison.Ordinal))
        {
            throw new ToolchainException("Bilinen SDL GPU flag düzeltmesi binding üreticisine uygulanamadı; beklenen anchor bulunamadı.");
        }

        text = text.Replace(
            anchor,
            $"{anchor}{Environment.NewLine}                \"{SimultaneousGpuTextureFlag}\",",
            StringComparison.Ordinal);
        File.WriteAllText(userProvidedData, text);
        Console.WriteLine($"Binding üreticisine proje düzeltmesi uygulandı: {SimultaneousGpuTextureFlag}");
    }

    private static void PatchTargetFramework(string projectFile)
    {
        var text = File.ReadAllText(projectFile);
        if (text.Contains("<TargetFramework>net10.0</TargetFramework>", StringComparison.Ordinal))
        {
            return;
        }

        if (!text.Contains("<TargetFramework>net8.0</TargetFramework>", StringComparison.Ordinal))
        {
            throw new ToolchainException($"Generator hedef framework'ü beklenen biçimde değil: {projectFile}");
        }

        File.WriteAllText(
            projectFile,
            text.Replace(
                "<TargetFramework>net8.0</TargetFramework>",
                "<TargetFramework>net10.0</TargetFramework>",
                StringComparison.Ordinal));
    }

    private string TransformGeneratedBinding(string upstream)
    {
        const string upstreamNamespace = "namespace SDL3;";
        const string upstreamClass = "public static unsafe partial class SDL";
        if (!upstream.Contains(upstreamNamespace, StringComparison.Ordinal) ||
            !upstream.Contains(upstreamClass, StringComparison.Ordinal))
        {
            throw new ToolchainException("Upstream binding şablonu değişmiş; namespace/class dönüşümü güvenle yapılamıyor.");
        }

        var newline = upstream.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        var generatedMarker = $"// NOTE: This file is auto-generated.{newline}";
        if (!upstream.Contains(generatedMarker, StringComparison.Ordinal))
        {
            throw new ToolchainException("Upstream binding generated-file başlığı bulunamadı.");
        }

        var provenanceHeader =
            $"// SDL source: {manifest.Sdl.Ref} ({manifest.Sdl.Commit}){newline}" +
            $"// Binding generator: flibitijibibo/SDL3-CS@{manifest.Bindings.GeneratorCommit}{newline}" +
            $"// Project generator patch: include {SimultaneousGpuTextureFlag} when present{newline}" +
            $"// This is project-adapted generated output, not an unmodified upstream source file.{newline}";

        var result = upstream.Replace(
            generatedMarker,
            $"{generatedMarker}{provenanceHeader}",
            StringComparison.Ordinal);
        result = result.Replace(upstreamNamespace, $"namespace {manifest.Bindings.Namespace};", StringComparison.Ordinal);
        result = result.Replace(upstreamClass, $"public static unsafe partial class {manifest.Bindings.ClassName}", StringComparison.Ordinal);
        return result;
    }

    private static Dictionary<string, int> CountWarnings(string binding)
    {
        return WarningRegex()
            .Matches(binding)
            .Select(match => match.Value)
            .GroupBy(value => value, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.Count(), StringComparer.Ordinal);
    }

    private void ValidateWarnings(Dictionary<string, int> actual)
    {
        var keys = manifest.Bindings.WarningBaseline.Keys
            .Concat(actual.Keys)
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();
        var differences = keys
            .Select(key => new
            {
                Key = key,
                Expected = manifest.Bindings.WarningBaseline.GetValueOrDefault(key),
                Actual = actual.GetValueOrDefault(key)
            })
            .Where(item => item.Expected != item.Actual)
            .ToArray();

        foreach (var key in keys)
        {
            Console.WriteLine($"Binding warning: {key} = {actual.GetValueOrDefault(key)} (baseline {manifest.Bindings.WarningBaseline.GetValueOrDefault(key)})");
        }

        if (differences.Length > 0 && !invocation.Has("--allow-binding-warnings"))
        {
            var details = string.Join(
                Environment.NewLine,
                differences.Select(item => $"  {item.Key}: baseline={item.Expected}, generated={item.Actual}"));
            throw new ToolchainException(
                "Binding warning baseline değişti. Üretilen dosya Framework'e yazılmadı. " +
                "Farkı inceleyin; bilinçli kabul için --allow-binding-warnings kullanın.\n" + details);
        }
    }

    private async Task WriteProvenanceAsync(
        string sdlRoot,
        string c2ffi,
        IReadOnlyDictionary<string, int> warnings,
        string binding)
    {
        var git = ProcessRunner.FindExecutable("git")!;
        var actualSdlCommit = await ProcessRunner.CaptureAsync(
            git,
            ["-C", sdlRoot, "rev-parse", "HEAD"],
            manifest.RepositoryRoot,
            cancellationToken);
        var provenance = new
        {
            generatedAtUtc = DateTimeOffset.UtcNow,
            sdlVersion = manifest.Sdl.Version,
            sdlRef = manifest.Sdl.Ref,
            sdlCommit = actualSdlCommit,
            bindingGeneratorCommit = manifest.Bindings.GeneratorCommit,
            c2ffiMode = invocation.Value("--c2ffi") is null ? "manifest-pinned-build" : "explicit-external-executable",
            expectedC2ffiCommit = manifest.Bindings.C2FfiCommit,
            projectGeneratorPatches = new[] { $"include {SimultaneousGpuTextureFlag} when present" },
            c2ffiExecutable = Path.GetFullPath(c2ffi),
            output = manifest.Bindings.Output,
            sha256 = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(binding))).ToLowerInvariant(),
            warnings
        };
        var path = Path.Combine(manifest.ArtifactsRoot, "provenance", "bindings.json");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllTextAsync(
            path,
            JsonSerializer.Serialize(provenance, new JsonSerializerOptions { WriteIndented = true }),
            cancellationToken);
    }

    private static void ReportGpuHelperStatus(string binding)
    {
        var match = BeginGpuRenderPassRegex().Match(binding);
        if (!match.Success)
        {
            Console.WriteLine("UYARI: SDL_BeginGPURenderPass üretilen binding içinde bulunamadı; SDL3.GPU.cs elle incelenmeli.");
            return;
        }

        var signature = match.Value;
        if (signature.Contains("in SDL_GPUDepthStencilTargetInfo", StringComparison.Ordinal))
        {
            Console.WriteLine("SDL3.GPU.cs durumu: depth-stencil parametresi hâlâ `in`; null geçiş helper'ı hâlâ gerekli.");
        }
        else if (signature.Contains("SDL_GPUDepthStencilTargetInfo*", StringComparison.Ordinal))
        {
            Console.WriteLine("SDL3.GPU.cs durumu: yeni binding pointer kabul ediyor; helper kaldırılmadan önce çağrı yerleri incelenebilir.");
        }
        else
        {
            Console.WriteLine("SDL3.GPU.cs durumu: imza beklenen biçimde değil; helper elle incelenmeli.");
        }
    }

    [GeneratedRegex(@"WARN_[A-Z_]+", RegexOptions.CultureInvariant)]
    private static partial Regex WarningRegex();

    [GeneratedRegex(@"public static partial IntPtr SDL_BeginGPURenderPass\([^;]+;", RegexOptions.CultureInvariant)]
    private static partial Regex BeginGpuRenderPassRegex();
}
